version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    ports:
      - "3307:3306"  # Mapuje port 3306 w kontenerze na port 3307 na hoście
    environment:
      MYSQL_ROOT_PASSWORD: root  # Ustawia hasło dla użytkownika root
    volumes:
      - mysql_data:/var/lib/mysql  # Persisting MySQL data

volumes:
  mysql_data:
